name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.23.x
          - 1.24.x
          - 1.25.x
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go}}
      - name: Download Go modules
        run: go mod download
      - name: Test Go code
        run: go test -v -race -covermode atomic -coverprofile coverage.out ./...
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          disable_search: true
          files: coverage.out
